LANGUAGE = "en"
PROTOCOL="http"
HOSTNAME = "thdc"

LANDING_PAGE = f"{PROTOCOL}://{HOSTNAME}/{LANGUAGE}/home"
LOGIN_PAGE = f"{PROTOCOL}://{HOSTNAME}/{LANGUAGE}/login"
REGISTER_PAGE = f"{PROTOCOL}://{HOSTNAME}/{LANGUAGE}/register"