name: Run Synthetic Tests


on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:  
  CheckIfRunning:
    uses: THD-C/The_THDc_App/.github/workflows/check-self-hosted-runner.yml@main
    secrets: inherit
  
  RunSyntheticTests:
    needs: CheckIfRunning
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python environment
        run: |
          python3 -m venv ./.venv
          source ./.venv/bin/activate
          pip install -r requirements.txt
          playwright install   
      
      - name: Run Synthetic Tests
        run: |
          source ./.venv/bin/activate
          python -m pytest -v -p no:warnings --reruns 3